Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters: 
      TemplateURL: String
      TimeoutInMinutes: Integer
  
  EKSClusterStack

  NodeInstanceProfileStack

  NodeSecurityGroupStack

  NodeASGStack








  